controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

chat_index:
    path: /chat
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: "admin/chat.html.twig"
